# Generated by Django 2.1.15 on 2020-06-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_birth',
            field=models.DateField(default='20200321'),
        ),
    ]
