# Generated by Django 2.1.15 on 2020-07-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200701_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_birth',
        ),
    ]
