# Generated by Django 2.1.15 on 2020-07-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_follewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_intro',
            field=models.CharField(default='안녕 나는 먹는건 싫어하는데 좋은거 먹는거 좋아해', max_length=40),
            preserve_default=False,
        ),
    ]
