# Generated by Django 2.1.15 on 2020-07-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200701_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_birth',
            field=models.DateField(),
        ),
    ]
