# Generated by Django 2.1.15 on 2020-07-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200701_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_birth',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
