# Generated by Django 2.1.15 on 2020-06-30 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('restaurant_address', models.CharField(max_length=30)),
                ('restaurant_name', models.CharField(max_length=30)),
                ('food_name', models.CharField(max_length=30)),
                ('food_review', models.CharField(default='nonono', max_length=100)),
                ('food_star', models.FloatField()),
                ('food_image', imagekit.models.fields.ProcessedImageField(upload_to='upload_photo')),
                ('visit_date', models.DateField(default='20200321')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
