# Generated by Django 2.1.15 on 2020-07-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='food_review',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='visit_date',
            field=models.DateField(),
        ),
    ]
