# Generated by Django 2.1.15 on 2020-06-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_auto_20200628_2110'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
