# Generated by Django 2.1.15 on 2020-06-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_profiel_image',
            new_name='user_profile_image',
        ),
    ]
