# Generated by Django 2.1.15 on 2020-07-02 11:03

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='food_ctg_image',
            field=imagekit.models.fields.ProcessedImageField(default='/img/ctg/chicken.png', upload_to='food_ctg_photo'),
        ),
    ]
