# Generated by Django 2.1.15 on 2020-06-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_ctg', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_ctgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.FoodCategory')),
            ],
        ),
    ]
