# Generated by Django 2.1.15 on 2020-06-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200629_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='food_review',
            field=models.CharField(default='nonono', max_length=300),
        ),
    ]
