# Generated by Django 2.1.15 on 2020-07-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_foodcategory_food_ctg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodchoice',
            name='status',
            field=models.CharField(default='일반', max_length=50),
        ),
    ]
