# Generated by Django 2.1.15 on 2020-06-28 12:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_profiel_image',
        ),
        migrations.AddField(
            model_name='user',
            name='user_profile_image',
            field=imagekit.models.fields.ProcessedImageField(default='default.png', upload_to='user_profile_image'),
        ),
    ]
