# Generated by Django 2.1.15 on 2020-07-03 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follewers',
            field=models.ManyToManyField(related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
