# Generated by Django 2.1.15 on 2020-07-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200701_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
    ]
