# Generated by Django 2.1.15 on 2020-07-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_review_food_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='food_kind',
            field=models.CharField(max_length=10),
        ),
    ]
