# Generated by Django 2.1.15 on 2020-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='food_review',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='food_star',
            field=models.IntegerField(),
        ),
    ]
