# Generated by Django 2.1.15 on 2020-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20200703_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='food_star',
            field=models.CharField(max_length=30),
        ),
    ]
