# Generated by Django 2.1.15 on 2020-07-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20200702_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='food_kind',
            field=models.CharField(default='korean', max_length=5),
            preserve_default=False,
        ),
    ]
