# Generated by Django 2.1.15 on 2020-07-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20200703_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='food_star',
            field=models.IntegerField(),
        ),
    ]
